# -*- coding: utf-8 -*-

# @Time:2022/0/
#@version:
# Created by: Python3.9.6
#@author:鹄思鹄想bit森
# WARNING: run again.  Do not edit this file unless you know what you are doing.

#研究桌面上表面光照强度的变化
import time
from mpython import *

time.sleep_ms(50)
print(('_TITLE','照度值'))
time.sleep_ms(50)
oled.fill(0)#掌控板oled清屏

while True:
    oled.show()
    oled.Dischar('照度值',0,0,1)
    print((light.read(),))
    time.sleep(0.5)