# -*- coding: utf-8 -*-

# @Time:2022/0/
#@version:
# Created by: Python3.9.6
#@author:鹄思鹄想bit森
# WARNING: run again.  Do not edit this file unless you know what you are doing.

import  numpy as np #调用库，使用库中的科学计算函数
'''初始化学生学习时间和学习成绩(x,y)的数据'''
x=[0.5,0.75,1,1.25,1.5,1.75,1.75,2,2.25]
y=[10,22,13,43,20,22,23,33,50]

'''通过已知数据点，求解线性模型中b0和b1两个参数'''
def fitSLR(x,y):
    n=len(x)#获取数据集长度
    dinominator=0#分母
    numerato=0#分子
    for i in range(0,n):
        numerato +=((x[i]-np.mean(x))*(y[i]-np.mean((y))))
        dinominator +=(x[i]-np.mean(x))**2
    b1=numerato/float(dinominator)#回归线斜率
    b0=np.mean(y)-b1*np.mean(x)
    return b0,b1
